esphome:
  name: ct1
  friendly_name: CT1 BLE Gateway


esp32:
  board: esp32dev
  flash_size: 4MB

  framework:
    type: esp-idf

    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLE_ENABLED: y



logger:
  baud_rate: 0



wifi:

  ssid: "CC"
  password: "chen1122"

  fast_connect: true

  power_save_mode: none


  ap:
    ssid: "CT1 Fallback"
    password: "12345678"



captive_portal:


web_server:


api:
  reboot_timeout: 0s



ota:
  - platform: esphome




mqtt:

  broker: "192.168.6.88"


  on_message:

    - topic: "ct1/ble/send"

      then:

        - lambda: |-

            id(ct1_ble).send_hex(x);





external_components:
  - source:
      type: local
      path: components


esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 30ms
    active: false


ble_gateway:
  id: ct1_ble
light:
  - platform: ble_light
    id: my_bedroom_light      # <--- 【新增】显式指定一个唯一的 ID
    name: "卧室灯"
    ble_device_id: "light.room1"
    gateway: ct1_ble
  
