esphome:
  name: ct1
  friendly_name: CT1 BLE Gateway

  includes:
    - ble_raw_gateway.h


esp32:
  board: esp32dev
  framework:
    type: esp-idf

    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y


logger:
  baud_rate: 0


wifi:
  ssid: "CC"
  password: "chen1122"

  fast_connect: true
  power_save_mode: none


captive_portal:


api:
  reboot_timeout: 0s


ota:
  - platform: esphome



mqtt:

  id: mqtt_client

  broker: "192.168.6.88"


  on_connect:

    then:

      - lambda: |-

          id(mqtt_client).publish(
            "ct1/status",
            "online"
          );



  on_message:

    - topic: ct1/ble/send

      then:

        - lambda: |-

            ble_send_raw_hex(
              x.c_str()
            );
