esphome:
  name: ct1
  friendly_name: CT1 BLE Gateway

  includes:
    - ble_raw_gateway.h


esp32:
  board: esp32dev
  flash_size: 4MB

  framework:
    type: esp-idf

    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y


logger:
  baud_rate: 0


wifi:
  ssid: "CC"
  password: "chen1122"

  fast_connect: true
  power_save_mode: none

  ap:
    ssid: "CT1 Fallback"
    password: "12345678"


captive_portal:


api:
  reboot_timeout: 0s


ota:
  - platform: esphome



# ======================
# BLE接收
# ======================

esp32_ble:

  io_capability: none



esp32_ble_tracker:

  scan_parameters:

    interval: 320ms
    window: 40ms
    active: false



  on_ble_advertise:

    then:

      - lambda: |-

          std::string raw;

          auto d = x.get_raw();


          for(auto b:d)
          {

            char buf[3];

            sprintf(buf,"%02X",b);

            raw += buf;

          }


          if(raw.length())
          {

            id(mqtt_client).publish(
              "ct1/ble/receive",
              raw
            );

          }





# ======================
# MQTT
# ======================

mqtt:

  id: mqtt_client


  broker: "192.168.6.10"




  on_connect:

    then:

      - lambda: |-

          id(mqtt_client).publish(
            "ct1/status",
            "online"
          );



  on_disconnect:

    then:

      - lambda: |-

          id(mqtt_client).publish(
            "ct1/status",
            "offline"
          );



  # HA发送任意BLE包

  on_message:


    - topic: ct1/ble/send


      then:

        - lambda: |-

            ble_send_raw_hex(
              x.c_str()
            );
