name: Build CT1 Firmware


on:

  workflow_dispatch:

  push:

    branches:
      - main



jobs:


  build:


    runs-on: ubuntu-latest


    steps:


      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4



      # 安装 ESPHome
      - name: Install ESPHome
        run: |

          python -m pip install --upgrade pip

          pip install esphome



      # 编译
      - name: Compile CT1
        run: |

          esphome compile ct1.yaml



      # 收集所有 bin
      - name: Collect firmware files
        run: |

          mkdir -p firmware


          find .esphome/build/ct1 \
          -type f \
          \( \
          -name "*.bin" \
          -o -name "*.elf" \
          -o -name "*.map" \
          \) \
          -exec cp {} firmware/ \;



          ls -lh firmware



      # 上传全部文件
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4

        with:

          name: CT1-firmware

          path: firmware/